### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dra2020/topojson-simplify/-/topojson-simplify-3.0.102.tgz

### ISSUE THREAD

**Issue by rootsmusic** [terrencecrowley/chronology#2]
I'm a novice in Bash, Git, node and npm.  I followed the [instructions to run](https://medium.com/dra-2020/using-dra-repositories-e53a99d85826) dra-analytics-app.  Why do I get an error when I run npm?  Thanks!

**Steps in Git Bash:**
1. `cd ~/Documents/GitHub/vtd_data/`
2. `git clone https://github.com/dra2020/dra-analytics`
3. `cd ~/Documents/GitHub/vtd_data/dra-analytics`
4. `git pull` says "already up to date".
5. `npm install` (attached log) returns the error:
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated text-encoding@0.6.4: no longer maintained
> npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dra2020/topojson-simplify/-/topojson-simplify-3.0.102.tgz - Not found
> npm ERR! 404
> npm ERR! 404  '@dra2020/topojson-simplify@https://registry.npmjs.org/@dra2020/topojson-simplify/-/topojson-simplify-3.0.102.tgz' is not in this registry.
6. `npm run build` returns the error:
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> 
> @dra2020/dra-analytics@4.0.0 build
> webpack
> 
> [webpack-cli] Failed to load 'C:\Users\admin\Documents\GitHub\vtd_data\dra-analytics\webpack.config.js' config
> [webpack-cli] Error: ENOENT: no such file or directory, scandir 'node_modules'
>     at Object.readdirSync (node:fs:1441:3)
>     at Object.<anonymous> (C:\Users\admin\Documents\GitHub\vtd_data\dra-analytics\webpack.config.js:6:4)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Module._load (node:internal/modules/cjs/loader:827:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at WebpackCLI.tryRequireThenImport (C:\Users\admin\node_modules\webpack-cli\lib\webpack-cli.js:204:22)
>     at loadConfigByPath (C:\Users\admin\node_modules\webpack-cli\lib\webpack-cli.js:1404:38) {
>   errno: -4058,
>   syscall: 'scandir',
>   code: 'ENOENT',
>   path: 'node_modules'
> }
7. `cd ~/Documents/GitHub/vtd_data/`
8. `git clone https://github.com/dra2020/dra-analytics-app`
9. `cd ~/Documents/GitHub/vtd_data/dra-analytics-app`
10. `git pull` says "already up to date".
11. `npm install` returns same error as in step 5.
12. `npm run test` returns the error:
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> 
> @alecramsay/redistricting-research@1.0.0 test
> node server
> 
> node:internal/modules/cjs/loader:942
>   throw err;
> 
> Error: Cannot find module './dist/server.bundle.js'
> Require stack:
> - C:\Users\admin\Documents\GitHub\vtd_data\dra-analytics-app\server.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
>     at Module._load (node:internal/modules/cjs/loader:780:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (C:\Users\admin\Documents\GitHub\vtd_data\dra-analytics-app\server.js:1:11)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Module._load (node:internal/modules/cjs/loader:827:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\admin\\Documents\\GitHub\\vtd_data\\dra-analytics-app\\server.js'
>   ]
> }
> Node.js v18.3.0

VERSIONS
Desktop: Windows 10
Git: 2.36.1.windows.1
nvm for Windows: 1.1.9
Node.js: 18.3.0
npm: 8.11.0
[2022-06-15T01_52_01_841Z-debug-0.log](https://github.com/terrencecrowley/chronology/files/8905173/2022-06-15T01_52_01_841Z-debug-0.log)

**Comment by rootsmusic** [comment]
@terrencecrowley Error in step 5 seems to be missing file from DRA2020.

**Comment by rootsmusic** [comment]
Moving issue to https://github.com/dra2020/dra-analytics/issues/6
